language: java
jdk:
  - openjdk8
before_install:
  - pip install --user codecov
before_script:
  - if [[ -z $TRAVIS_COMMIT_RANGE ]]; then TRAVIS_COMMIT_RANGE=$(git rev-parse master)...$(git rev-parse HEAD); fi
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then nondextests=""; else nondextests=$(git diff --name-status $TRAVIS_COMMIT_RANGE | grep /test/ | sed -e 's;.*test/java/;;' -e 's/.java//' -e 's;/;.;g' | tr '\n' ','); fi
script:
  # - echo $TRAVIS_COMMIT_RANGE
  # - echo $TRAVIS_EVENT_TYPE
  # - echo $nondextests
  - if [ "$TRAVIS_EVENT_TYPE" == "cron" ] || [ ! -z $nondextests ]; then travis_wait 30 mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn edu.illinois:nondex-maven-plugin:1.1.2:nondex -DnondexSeed=$RANDOM -DnondexRuns=10 -DfailIfNoTests=false -Dtest=cz.habarta.typescript.generator.Jackson1ParserTest#test > /dev/null 2>&1 ; fi  
  - if [ -d ".nondex" ]; then flakyTests=$(awk ' !x[$0]++' .nondex/*/failures); fi
  # - echo $flakyTests
  - if [ ! -z "$flakyTests" ]; then printf "Found flaky tests:\n$flakyTests \n" ; exit 1 ; fi
after_success:
  - codecov
branches:
  except:
    - appveyor
Â© 2021 GitHub, Inc.
Terms
